#pragma once

#include "hw/hw.h"
#include "hw/sysbus.h"
#include "hw/registerfields.h"

#define TYPE_ESP32_RTC_CNTL "misc.esp32.rtc_cntl"
#define ESP32_RTC_CNTL(obj) OBJECT_CHECK(Esp32RtcCntlState, (obj), TYPE_ESP32_RTC_CNTL)

#define ESP32_RTC_DIG_RESET_GPIO    "dig-reset"
#define ESP32_RTC_CPU_RESET_GPIO    "cpu-reset"
#define ESP32_RTC_CPU_STALL_GPIO    "cpu-stall"
#define ESP32_RTC_CLK_UPDATE_GPIO   "clk-update"
#define ESP32_ULP_TIMER_GPIO        "enable-gpio-timer"
#define ESP32_RTC_WAKEUP_GPIO       "rtc-wakeup"

typedef enum Esp32ResetCause {
    ESP32_POWERON_RESET = 1,
    ESP32_SW_SYS_RESET = 3,
    ESP32_OWDT_RESET = 4,
    ESP32_DEEPSLEEP_RESET = 5,
    ESP32_SDIO_RESET = 6,
    ESP32_TG0WDT_SYS_RESET = 7,
    ESP32_TG1WDT_SYS_RESET = 8,
    ESP32_RTCWDT_SYS_RESET = 9,
    ESP32_TGWDT_CPU_RESET = 11,
    ESP32_SW_CPU_RESET = 12,
    ESP32_RTCWDT_CPU_RESET = 13,
    ESP32_EXT_CPU_RESET = 14,
    ESP32_RTCWDT_BROWN_OUT_RESET = 15,
    ESP32_RTCWDT_RTC_RESET = 16
} Esp32ResetCause;

#define RTC_EXT0_TRIG_EN    BIT(0)  //!< EXT0 GPIO wakeup
#define RTC_EXT1_TRIG_EN    BIT(1)  //!< EXT1 GPIO wakeup
#define RTC_GPIO_TRIG_EN    BIT(2)  //!< GPIO wakeup (light sleep only)
#define RTC_TIMER_TRIG_EN   BIT(3)  //!< Timer wakeup
#define RTC_SDIO_TRIG_EN    BIT(4)  //!< SDIO wakeup (light sleep only)
#define RTC_MAC_TRIG_EN     BIT(5)  //!< MAC wakeup (light sleep only)
#define RTC_UART0_TRIG_EN   BIT(6)  //!< UART0 wakeup (light sleep only)
#define RTC_UART1_TRIG_EN   BIT(7)  //!< UART1 wakeup (light sleep only)
#define RTC_TOUCH_TRIG_EN   BIT(8)  //!< Touch wakeup
#define RTC_ULP_TRIG_EN     BIT(9)  //!< ULP wakeup
#define RTC_BT_TRIG_EN      BIT(10) //!< BT wakeup (light sleep only)



typedef enum Esp32SocClkSel {
    ESP32_SOC_CLK_XTAL = 0,
    ESP32_SOC_CLK_PLL = 1,
    ESP32_SOC_CLK_8M = 2,
    ESP32_SOC_CLK_APLL = 3
} Esp32SocClkSel;

typedef enum Esp32FastClkSel {
    ESP32_FAST_CLK_XTALD4 = 0,
    ESP32_FAST_CLK_8M = 1
} Esp32FastClkSel;

typedef enum Esp32SlowClkSel {
    ESP32_SLOW_CLK_RC = 0,
    ESP32_SLOW_CLK_32KXTAL = 1,
    ESP32_SLOW_CLK_8MD256 = 2
} Esp32SlowClkSel;

typedef struct Esp32RtcCntlState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    qemu_irq irq;
    qemu_irq dig_reset_req;
    qemu_irq cpu_reset_req[ESP32_CPU_COUNT];
    qemu_irq cpu_stall_req[ESP32_CPU_COUNT];
    qemu_irq clk_update;
    qemu_irq enable_ulp_timer;
    qemu_irq rtc_wakeup;
    bool cpu_stall_state[ESP32_CPU_COUNT];

    uint32_t xtal_apb_freq;
    uint32_t pll_apb_freq;
    Esp32SocClkSel soc_clk;
    Esp32FastClkSel rtc_fastclk;
    uint32_t rtc_fastclk_freq;
    Esp32SlowClkSel rtc_slowclk;
    uint32_t rtc_slowclk_freq;
    int64_t time_base_ns;
    uint32_t state0;

    uint32_t options0_reg;
    uint64_t time_reg;
    uint32_t sleep_timer0_reg;
    uint32_t sleep_timer1_reg;
    uint32_t sw_cpu_stall_reg;
    uint32_t wakeup_state_reg;
    uint32_t wakeup_conf;
    uint32_t ext_wakeup1;
    uint32_t low_power_state_reg;
    uint32_t scratch_reg[ESP32_RTC_CNTL_SCRATCH_REG_COUNT];
    uint32_t mem_conf;
    uint32_t int_raw;
    uint32_t int_en;
    uint32_t sdio_conf;
    uint32_t dig_pwc;
    Esp32ResetCause reset_cause[ESP32_CPU_COUNT];
    bool stat_vector_sel[ESP32_CPU_COUNT];
    QEMUTimer sleep_timer;
} Esp32RtcCntlState;

REG32(RTC_CNTL_OPTIONS0, 0x00)
    FIELD(RTC_CNTL_OPTIONS0, SW_SYS_RESET, 31, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_PROCPU_RESET, 5, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_APPCPU_RESET, 4, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_STALL_PROCPU_C0, 2, 2)
    FIELD(RTC_CNTL_OPTIONS0, SW_STALL_APPCPU_C0, 0, 2)

REG32(RTC_CNTL_SLEEP_TIMER0, 0x4)
REG32(RTC_CNTL_SLEEP_TIMER1, 0x8)
    FIELD(RTC_CNTL_SLEEP_TIMER1, VAL_HI, 0, 16)
    FIELD(RTC_CNTL_SLEEP_TIMER1, ALARM_EN, 16, 1)

REG32(RTC_CNTL_TIME_UPDATE, 0xc)
    FIELD(RTC_CNTL_TIME_UPDATE, UPDATE, 31, 1)
    FIELD(RTC_CNTL_TIME_UPDATE, VALID, 30, 1)
REG32(RTC_CNTL_TIME0, 0x10)
REG32(RTC_CNTL_TIME1, 0x14)

REG32(RTC_CNTL_STATE0, 0x18)
    FIELD(RTC_CNTL_STATE0,SLEEP_EN,31,1)
    FIELD(RTC_CNTL_STATE0,ULP_TIMER_EN,24,1)

REG32(RTC_CNTL_RESET_STATE, 0x34)
    FIELD(RTC_CNTL_RESET_STATE, PROCPU_STAT_VECTOR_SEL, 13, 1)
    FIELD(RTC_CNTL_RESET_STATE, APPCPU_STAT_VECTOR_SEL, 12, 1)
    FIELD(RTC_CNTL_RESET_STATE, RESET_CAUSE_APPCPU, 6, 6)
    FIELD(RTC_CNTL_RESET_STATE, RESET_CAUSE_PROCPU, 0, 6)

REG32(RTC_CNTL_WAKEUP_STATE, 0x38)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_CAUSE, 0,11)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA, 11,11)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA_EXT0, 11,1)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA_EXT1, 12,1)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA_GPIO, 13,1)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA_RTC_TIMER, 14,1)
    FIELD(RTC_CNTL_WAKEUP_STATE, GPIO_WAKEUP_FILTER, 22,1)

REG32(RTC_CNTL_INT_ENA, 0x3c)
    FIELD(RTC_CNTL_INT_ENA, SLP_WAKEUP_INT,0,1)
    FIELD(RTC_CNTL_INT_ENA, SLP_REJECT_INT,1,1)

REG32(RTC_CNTL_INT_RAW, 0x40)
    FIELD(RTC_CNTL_INT_RAW, SLP_WAKEUP_INT,0,1)
    FIELD(RTC_CNTL_INT_RAW, SLP_REJECT_INT,1,1)

REG32(RTC_CNTL_INT_ST, 0x44)
    FIELD(RTC_CNTL_INT_ST, SLP_WAKEUP_INT,0,1)
    FIELD(RTC_CNTL_INT_ST, SLP_REJECT_INT,1,1)

REG32(RTC_CNTL_INT_CLR, 0x48)
    FIELD(RTC_CNTL_INT_CLR, SLP_WAKEUP_INT,0,1)
    FIELD(RTC_CNTL_INT_CLR, SLP_REJECT_INT,1,1)

REG32(RTC_CNTL_STORE0, 0x4c)
REG32(RTC_CNTL_STORE1, 0x50)
REG32(RTC_CNTL_STORE2, 0x54)
REG32(RTC_CNTL_STORE3, 0x58)

REG32(RTC_CNTL_EXT_WAKEUP_CONF, 0x60)
    FIELD(RTC_CNTL_EXT_WAKEUP_CONF, WAKEUP0LV, 30,1)
    FIELD(RTC_CNTL_EXT_WAKEUP_CONF, WAKEUP1LV, 31,1)

REG32(RTC_CNTL_CLK_CONF, 0x70)
    FIELD(RTC_CNTL_CLK_CONF, ANA_CLK_RTC_SEL, 30, 2)
    FIELD(RTC_CNTL_CLK_CONF, FAST_CLK_RTC_SEL, 29, 1)
    FIELD(RTC_CNTL_CLK_CONF, SOC_CLK_SEL, 27, 2)

REG32(RTC_CNTL_SDIO_CONF, 0x74)
    FIELD(RTC_CNTL_SDIO_CONF, VREG_PD_EN, 21, 1)

REG32(RTC_CNTL_DIG_PWC, 0x84)
    FIELD(RTC_CNTL_DIG_PWC, DG_WRAP_PD_EN, 31, 1)

REG32(RTC_CNTL_SW_CPU_STALL, 0xac)
    FIELD(RTC_CNTL_SW_CPU_STALL, PROCPU_C1, 26, 6)
    FIELD(RTC_CNTL_SW_CPU_STALL, APPCPU_C1, 20, 6)

REG32(RTC_CNTL_STORE4, 0xb0)
REG32(RTC_CNTL_STORE5, 0xb4)
REG32(RTC_CNTL_STORE6, 0xb8)
REG32(RTC_CNTL_STORE7, 0xbc)

REG32(RTC_CNTL_LOW_POWER_ST_REG, 0xc0)
    FIELD(RTC_CNTL_LOW_POWER_ST_REG, RTC_RDY_FOR_WAKEUP, 19,1)

REG32(RTC_CNTL_EXT_WAKEUP1, 0xcc)
    FIELD(RTC_CNTL_EXT_WAKEUP1, SEL, 0, 18)

REG32(RTC_CNTL_ULP_CP_TIMER, 0xfc)
    FIELD(RTC_CNTL_ULP_CP_TIMER,PC_INIT,0,11)
    FIELD(RTC_CNTL_ULP_CP_TIMER,GPIO_WAKEUP_ENA, 29,1)
    FIELD(RTC_CNTL_ULP_CP_TIMER,GPIO_WAKEUP_CLR, 30,1)
    FIELD(RTC_CNTL_ULP_CP_TIMER,SLP_TIMER_EN, 31,1)

REG32(RTC_MEM_CONF, 0x100)
    FIELD(RTC_MEM_CONF, CRC_FINISH, 31,1)
    FIELD(RTC_MEM_CONF, CRC_LEN, 20,11)
    FIELD(RTC_MEM_CONF, CRC_ADDR, 9,11)
    FIELD(RTC_MEM_CONF, CRC_START, 8,1)
    FIELD(RTC_MEM_CONF, PID_CONF, 0,8)
REG32(RTC_CNTL_DATE,   0x13c)

#define ESP32_RTC_CNTL_SIZE (A_RTC_CNTL_DATE + 4)
