name: 'Simple build for Linux'

on: [push, pull_request]

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt-get install -y -q --no-install-recommends \
	    build-essential \
	    libgcrypt-dev \
	    libglib2.0-dev \
	    libpixman-1-dev \
	    libsdl2-dev \
	    libslirp-dev \
	    ninja-build \
	    python3-pip \
	    libvte-2.91-dev \
	    wget \
	    zlib1g-dev
	    # libgtk-3-dev # only needed for --enable-gtk
	    # git \

      - name: Compile it
        run: |
          cat /proc/cpuinfo
          make -j4 # how many cores?

      - name: Dist artifacts (${{ matrix.target }} @ ${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        with:
          name: qemu-system-xtensa
          path: build/qemu-system-xtensa


